// <auto-generated />
namespace SkinsModulo17e.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class catalisador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catalisador));
        
        string IMigrationMetadata.Id
        {
            get { return "202303021037003_catalisador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
